### ISSUE TITLE
IO Error not handled

### ISSUE THREAD

**Issue by iwanders** [iwanders/IR_control#1]
The following error occurs from time to time, perhaps when the MCU resets? Shouldn't PySerial handle this gracefully?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "../ir_control/interface.py", line 144, in run
    self._process_rx()  # read from serial port
  File "../ir_control/interface.py", line 99, in _process_rx
    if (self.ser.inWaiting()):
  File "/usr/local/lib/python3.2/dist-packages/serial/serialutil.py", line 518, in inWaiting
    return self.in_waiting
  File "/usr/local/lib/python3.2/dist-packages/serial/serialposix.py", line 429, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 5] Input/output error
```

Regardless, this should be handled gracefully.

**Comment by iwanders** [comment]
Closed by #2.
